apiVersion: apps/v1
kind: Deployment
metadata:
  name: role
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: role
  replicas: 1
  template:
    metadata:
      labels:
        app: role
    spec:
      containers:
        - name: role
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/role:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8093
