apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
