package com.ngdesk.module.template;



import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.ngdesk.commons.annotations.CustomNotEmpty;
import com.ngdesk.commons.annotations.CustomNotNull;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class HtmlTemplate {
	
	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	@JsonProperty("TEMPLATE_ID")
	private String id;
	
	@Schema(required = true, description = "module id of the module to which the html template belongs to")
	@JsonProperty("MODULE")
	@Field("MODULE")
	@CustomNotNull(message = "NOT_NULL", values = { "MODULE" })
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "MODULE" })
	private String moduleId;
	
	
	@Schema(description = "Html template to generate PDF", required = true, example = "<html><head><title> This is a test<\\/title><\\/head><body><h1 style=\\\"color:green\\\">First Paragraph <\\/h1><p style=\\\"color:blue\\\" >We are just testing simple html first<br><\\/br>then we will include rest of the things.<\\/p><\\/body><\\/html>")
	@Field("HTML_TEMPLATE")
	@JsonProperty("HTML_TEMPLATE")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "HTML_TEMPLATE" })
	@CustomNotNull(message = "NOT_NULL", values = { "HTML_TEMPLATE" })
	private String htmlTemplate;
	
	@Schema(description = "Name of the html template", required = true, example = "Quotes Template")
	@Field("TITLE")
	@JsonProperty("TITLE")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "TITLE" })
	private String name;
	

	public HtmlTemplate() {
		super();
	}

	public HtmlTemplate(String id, String moduleId,String htmlTemplate, String name) {
		super();
		this.id = id;
		this.moduleId = moduleId;
		this.htmlTemplate = htmlTemplate;
		this.name = name;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getModuleId() {
		return moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	public String getHtmlTemplate() {
		return htmlTemplate;
	}

	public void setHtmlTemplate(String htmlTemplate) {
		this.htmlTemplate = htmlTemplate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	

}
