package com.ngdesk.sam.discoveryrules.dao;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.Pattern;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ngdesk.commons.annotations.CustomNotEmpty;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class DiscoveryRule {

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	@JsonProperty("DISCOVERY_RULE_ID")
	private String id;

	@Schema(description = "Unique ID for each company", required = true, hidden = true)
	@Field("COMPANY_ID")
	@JsonProperty("COMPANY_ID")
	private String companyID;

	@Schema(description = "File name of the discovery rules", required = true, example = "ngDesk discovery")
	@Field("FILE_NAME")
	@JsonProperty("FILE_NAME")
	private String fileName;

	@Schema(description = "Hash values", required = false)
	@Field("HASH")
	@JsonProperty("HASH")
	private String hash;

	@Schema(description = "Rule type of the discovery rules", required = true, example = "Discovery rule")
	@Field("RULE_TYPE")
	@JsonProperty("RULE_TYPE")
	@Pattern(regexp = "COMMAND|FILE", message = "INVALID_RULE_TYPE")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "DISCOVERY_RULE_RULE_TYPE" })
	private String ruleType;

	@Schema(description = "Operating system of the discovery rules", required = true, example = "windows")
	@Field("OS")
	@JsonProperty("OS")
	@Pattern(regexp = "Windows|Linux|Mac", message = "INVALID_OS_TYPE")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "DISCOVERY_RULE_OS" })
	private String os;

	@Schema(description = "Distribution type of linux", required = false, example = "fedora, red hat, debian")
	@Field("DISTRIBUTION_TYPE")
	@JsonProperty("DISTRIBUTION_TYPE")
	@Pattern(regexp = "fedora|red hat|debian", message = "INVALID_OS_TYPE")
	private String distributionType;

	@Schema(description = "Vendor of the discovery rule", required = true, example = "vendor")
	@Field("VENDOR")
	@JsonProperty("VENDOR")
	private String vendor;

	@Schema(description = "Command for the discovery rule", required = false)
	@Field("COMMAND")
	@JsonProperty("COMMAND")
	private List<String> command;

	@Schema(description = "Javascript for the discovery rule", required = false)
	@Field("JAVASCRIPT")
	@JsonProperty("JAVASCRIPT")
	private String javascript;

	@Schema(description = "Date Created", required = false, accessMode = AccessMode.READ_ONLY)
	@JsonProperty("DATE_CREATED")
	@Field("DATE_CREATED")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	private Date dateCreated;

	@Schema(description = "Date Updated", required = false, accessMode = AccessMode.READ_ONLY)
	@JsonProperty("DATE_UPDATED")
	@Field("DATE_UPDATED")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	private Date dateUpdated;

	@Schema(description = "Last Updated By", required = false, accessMode = AccessMode.READ_ONLY)
	@JsonProperty("LAST_UPDATED_BY")
	@Field("LAST_UPDATED_BY")
	private String lastUpdated;

	@Schema(description = "Created By", required = false, accessMode = AccessMode.READ_ONLY)
	@JsonProperty("CREATED_BY")
	@Field("CREATED_BY")
	private String createdBy;

	public DiscoveryRule() {

	}

	public DiscoveryRule(String id, String companyID, String fileName, String hash,
			@Pattern(regexp = "COMMAND|FILE", message = "INVALID_RULE_TYPE") String ruleType,
			@Pattern(regexp = "Windows|Linux|Mac", message = "INVALID_OS_TYPE") String os,
			@Pattern(regexp = "fedora|red hat|debian", message = "INVALID_OS_TYPE") String distributionType,
			String vendor, List<String> command, String javascript, Date dateCreated, Date dateUpdated,
			String lastUpdated, String createdBy) {
		super();
		this.id = id;
		this.companyID = companyID;
		this.fileName = fileName;
		this.hash = hash;
		this.ruleType = ruleType;
		this.os = os;
		this.distributionType = distributionType;
		this.vendor = vendor;
		this.command = command;
		this.javascript = javascript;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCompanyID() {
		return companyID;
	}

	public void setCompanyID(String companyID) {
		this.companyID = companyID;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getHash() {
		return hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public String getRuleType() {
		return ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	public String getOs() {
		return os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getDistributionType() {
		return distributionType;
	}

	public void setDistributionType(String distributionType) {
		this.distributionType = distributionType;
	}

	public String getVendor() {
		return vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	public List<String> getCommand() {
		return command;
	}

	public void setCommand(List<String> command) {
		this.command = command;
	}

	public String getJavascript() {
		return javascript;
	}

	public void setJavascript(String javascript) {
		this.javascript = javascript;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
