apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: image-registry.openshift-image-registry.svc:5000/NAMESPACE_REPLACE/config-server:1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
              initialDelaySeconds: 3
              periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
              initialDelaySeconds: 3
              periodSeconds: 3
          ports:
            - containerPort: 8888
