apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: websocket
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
