apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: company
  replicas: 1
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/company:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
