apiVersion: v1
data:
  consul-agent.json: |
    {
      "retry_join": [
         "10.2.15.90:8301",
         "10.2.15.91:8301",
         "110.2.15.92:8301"
      ],
      "rejoin_after_leave": true,
      "datacenter": "dc1",
      "encrypt": "v/N1vFJ2asjsJN2nLU1Ngw==",
      "services": [
        {
          "name": "nginx",
          "port": 443,
          "tags": [
            "nginx",
            "pre"
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-01-28T17:19:02Z"
  labels:
    app: nginx
    tier: frontend
    track: pre
  name: consul-agent-nginx
