package com.ngdesk.knowledgebase.article.dao;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.Size;

import org.springframework.data.annotation.Id;

import com.ngdesk.commons.annotations.CustomNotEmpty;
import com.ngdesk.commons.annotations.CustomNotNull;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class Article {

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	private String articleId;

	@Schema(required = true, description = "Title of article")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "ARTICLE_TITLE" })
	private String title;

	@Schema(required = true, description = "Body of article")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "ARTICLE_BODY" })
	private String body;

	@Schema(required = true, description = "Author of article")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "ARTICLE_AUTHOR" })
	private String author;

	@Schema(required = true, description = "List of team that can see the article")
	@CustomNotNull(message = "NOT_NULL", values = { "ARTICLE_VISIBLE_TO" })
	@Size(min = 1, message = "Visible To must contain at least one team")
	private List<String> visibleTo;

	@Schema(required = false, description = "boolean if article can receive comment")
	private boolean openForComments;

	@Schema(required = true, description = "Language needed to work")
	@Size(min = 2, max = 2, message = "Source language must be 2 characters")
	private String sourceLanguage;// :String(max and min 2 characters),

	@Schema(required = false, description = "Labels associated to the article")
	private List<String> labels;

	@Schema(required = false, description = "")
	private int order;

	@Schema(required = true, description = "Section in which the article belongs")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "ARTICLE_SECTION" })
	private String section;

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Date of creation of the article")
	private Date dateCreated;

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Last date the article was updated")
	private Date dateUpdated;

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Last updated by")
	private String lastUpdatedBy;

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "created by")
	private String createdBy;

	@Schema(required = false, description = "Publish")
	private boolean publish;

	@Schema(required = false, description = "comments")
	private List<CommentMessage> comments;

	@Schema(required = false, description = "attachments")
	private List<Attachment> attachments;

	public Article() {
	}

	public Article(String articleId, String title, String body, String author, List<String> visibleTo,
			boolean openForComments, String sourceLanguage, List<String> labels, int order, String section,
			Date dateCreated, Date dateUpdated, String lastUpdatedBy, String createdBy, boolean publish,
			List<CommentMessage> comments, List<Attachment> attachments) {
		super();
		this.articleId = articleId;
		this.title = title;
		this.body = body;
		this.author = author;
		this.visibleTo = visibleTo;
		this.openForComments = openForComments;
		this.sourceLanguage = sourceLanguage;
		this.labels = labels;
		this.order = order;
		this.section = section;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
		this.createdBy = createdBy;
		this.publish = publish;
		this.comments = comments;
		this.attachments = attachments;
	}

	public String getArticleId() {
		return articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public List<String> getVisibleTo() {
		return visibleTo;
	}

	public void setVisibleTo(List<String> visibleTo) {
		this.visibleTo = visibleTo;
	}

	public boolean isOpenForComments() {
		return openForComments;
	}

	public void setOpenForComments(boolean openForComments) {
		this.openForComments = openForComments;
	}

	public String getSourceLanguage() {
		return sourceLanguage;
	}

	public void setSourceLanguage(String sourceLanguage) {
		this.sourceLanguage = sourceLanguage;
	}

	public List<String> getLabels() {
		return labels;
	}

	public void setLabels(List<String> labels) {
		this.labels = labels;
	}

	public int getOrder() {
		return order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	public String getSection() {
		return section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public boolean isPublish() {
		return publish;
	}

	public void setPublish(boolean publish) {
		this.publish = publish;
	}

	public List<CommentMessage> getComments() {
		return comments;
	}

	public void setComments(List<CommentMessage> comments) {
		this.comments = comments;
	}

	public List<Attachment> getAttachments() {
		return attachments;
	}

	public void setAttachments(List<Attachment> attachments) {
		this.attachments = attachments;
	}
}
