apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: websocket
  replicas: 1
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/websocket:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
