apiVersion: v1
kind: Service
metadata:
  name: schedule-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: schedule
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
