package com.ngdesk.module.dao;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.Pattern;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.ngdesk.commons.annotations.CustomNotEmpty;
import com.ngdesk.commons.annotations.CustomNotNull;
import com.ngdesk.module.field.dao.ModuleField;
import com.ngdesk.module.layout.dao.CreateEditLayout;
import com.ngdesk.module.layout.dao.ListLayout;
import com.ngdesk.module.mobile.layout.dao.CreateEditMobileLayout;
import com.ngdesk.module.mobile.layout.dao.ListMobileLayout;
import com.ngdesk.module.validations.dao.ModuleValidation;
import com.ngdesk.workflow.dao.Workflow;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class Module {

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	@JsonProperty("MODULE_ID")
	private String moduleId;

	@Schema(description = "Name of the module", required = true, example = "books")
	@Field("NAME")
	@JsonProperty("NAME")
	@Pattern(regexp = "^[a-zA-Z0-9_ ]*$", message = "INVALID_MODULE_NAME")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "MODULE_NAME" })
	private String name;

	@JsonProperty("PARENT_MODULE")
	@Field("PARENT_MODULE")
	private String parentModule;

	@Schema(description = "Description of the module", required = false, example = "Module to handle books")
	@Field("DESCRIPTION")
	@JsonProperty("DESCRIPTION")
	private String description;

	@Field("SINGULAR_NAME")
	@JsonProperty("SINGULAR_NAME")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "SINGULAR_NAME" })
	private String singular;

	@Field("PLURAL_NAME")
	@JsonProperty("PLURAL_NAME")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "PLURAL_NAME" })
	private String plural;

	@JsonProperty("VALIDATIONS")
	@Field("VALIDATIONS")
	private List<ModuleValidation> validations;

	@JsonProperty("FIELDS")
	@Field("FIELDS")
	private List<ModuleField> fields;

	@Field("LIST_LAYOUTS")
	@JsonProperty("LIST_LAYOUTS")
	private List<ListLayout> listLayout;

	@Field("CREATE_LAYOUTS")
	@JsonProperty("CREATE_LAYOUTS")
	private List<CreateEditLayout> createLayout;

	@Field("EDIT_LAYOUTS")
	@JsonProperty("EDIT_LAYOUTS")
	private List<CreateEditLayout> editLayout;

	@Field("LIST_MOBILE_LAYOUTS")
	@JsonProperty("LIST_MOBILE_LAYOUTS")
	private List<ListMobileLayout> listMobileLayouts;

	@Field("CREATE_MOBILE_LAYOUTS")
	@JsonProperty("CREATE_MOBILE_LAYOUTS")
	private List<CreateEditMobileLayout> createMobileLayout;

	@Field("EDIT_MOBILE_LAYOUTS")
	@JsonProperty("EDIT_MOBILE_LAYOUTS")
	private List<CreateEditMobileLayout> editMobileLayout;

	@JsonProperty("DATE_CREATED")
	@Field("DATE_CREATED")
	private Date dateCreated;

	@JsonProperty("DATE_UPDATED")
	@Field("DATE_UPDATED")
	private Date dateUpdated;

	@JsonProperty("CREATED_BY")
	@Field("CREATED_BY")
	private String createdBy;

	@JsonProperty("LAST_UPDATED_BY")
	@Field("LAST_UPDATED_BY")
	private String lastUpdatedBy;

	public Module() {
	}

	public Module(String moduleId, @Pattern(regexp = "^[a-zA-Z0-9_ ]*$", message = "INVALID_MODULE_NAME") String name,
			String parentModule, String description, String singular, String plural, List<ModuleValidation> validations,
			List<ModuleField> fields, List<ListLayout> listLayout, List<CreateEditLayout> createLayout,
			List<CreateEditLayout> editLayout, List<ListMobileLayout> listMobileLayouts,
			List<CreateEditMobileLayout> createMobileLayout, List<CreateEditMobileLayout> editMobileLayout,
			Date dateCreated, Date dateUpdated, String createdBy, String lastUpdatedBy) {
		super();
		this.moduleId = moduleId;
		this.name = name;
		this.parentModule = parentModule;
		this.description = description;
		this.singular = singular;
		this.plural = plural;
		this.validations = validations;
		this.fields = fields;
		this.listLayout = listLayout;
		this.createLayout = createLayout;
		this.editLayout = editLayout;
		this.listMobileLayouts = listMobileLayouts;
		this.createMobileLayout = createMobileLayout;
		this.editMobileLayout = editMobileLayout;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getModuleId() {
		return moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getParentModule() {
		return parentModule;
	}

	public void setParentModule(String parentModule) {
		this.parentModule = parentModule;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSingular() {
		return singular;
	}

	public void setSingular(String singular) {
		this.singular = singular;
	}

	public String getPlural() {
		return plural;
	}

	public void setPlural(String plural) {
		this.plural = plural;
	}

	public List<ModuleValidation> getValidations() {
		return validations;
	}

	public void setValidations(List<ModuleValidation> validations) {
		this.validations = validations;
	}

	public List<ModuleField> getFields() {
		return fields;
	}

	public void setFields(List<ModuleField> fields) {
		this.fields = fields;
	}

	public List<ListLayout> getListLayout() {
		return listLayout;
	}

	public void setListLayout(List<ListLayout> listLayout) {
		this.listLayout = listLayout;
	}

	public List<CreateEditLayout> getCreateLayout() {
		return createLayout;
	}

	public void setCreateLayout(List<CreateEditLayout> createLayout) {
		this.createLayout = createLayout;
	}

	public List<CreateEditLayout> getEditLayout() {
		return editLayout;
	}

	public void setEditLayout(List<CreateEditLayout> editLayout) {
		this.editLayout = editLayout;
	}

	public List<ListMobileLayout> getListMobileLayouts() {
		return listMobileLayouts;
	}

	public void setListMobileLayouts(List<ListMobileLayout> listMobileLayouts) {
		this.listMobileLayouts = listMobileLayouts;
	}

	public List<CreateEditMobileLayout> getCreateMobileLayout() {
		return createMobileLayout;
	}

	public void setCreateMobileLayout(List<CreateEditMobileLayout> createMobileLayout) {
		this.createMobileLayout = createMobileLayout;
	}

	public List<CreateEditMobileLayout> getEditMobileLayout() {
		return editMobileLayout;
	}

	public void setEditMobileLayout(List<CreateEditMobileLayout> editMobileLayout) {
		this.editMobileLayout = editMobileLayout;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
