/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Escalate to users, schedules or teams
 */
export interface EscalateTo { 
    /**
     * List of schedule Ids
     */
    SCHEDULE_IDS?: Array<string>;
    /**
     * List of user Ids
     */
    USER_IDS?: Array<string>;
    /**
     * List of team Ids
     */
    TEAM_IDS?: Array<string>;
}

