apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk-gateway:latest
          imagePullPolicy: Always
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          ports:
            - containerPort: 8443
            
            
