package com.ngdesk.workflow.signaturedocument.dao;

import java.util.Date;

import org.springframework.data.annotation.Id;

import com.ngdesk.commons.annotations.CustomNotEmpty;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class SignatureDocument {

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	private String templateId;

	@Schema(required = true, accessMode = AccessMode.READ_ONLY, description = "company id of the company to which the signature document belongs to")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "COMPANY_ID" })
	private String companyId;

	@Schema(required = true, description = "Html Document")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "HTML_DOCUMENT" })
	private String htmlDocument;

	@Schema(required = true, description = "DateId of signature document")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "DATA_ID" })
	private String dataId;

	@Schema(required = true, description = "module id of the module to which the html template belongs to")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "MODULE" })
	private String moduleId;

	@Schema(required = true, description = "Name of the html template")
	private String name;

	@Schema(required = true, description = "Document signed")
	private Boolean signed;

	@Schema(required = false, description = "Date of signature document created")
	private Date dateCreated;

	@Schema(required = false, description = "Date of signature document signed")
	private Date dateSigned;

	@Schema(required = true, description = "Email address of the person to whom the mail has been sent")
	private String emailAddress;

	@Schema(required = true, description = "File upload field id")
	private String fieldId;

	public SignatureDocument() {

	}

	public SignatureDocument(String templateId, String companyId, String htmlDocument, String dataId, String moduleId,
			String name, Boolean signed, Date dateCreated, Date dateSigned, String emailAddress, String fieldId) {
		super();
		this.templateId = templateId;
		this.companyId = companyId;
		this.htmlDocument = htmlDocument;
		this.dataId = dataId;
		this.moduleId = moduleId;
		this.name = name;
		this.signed = signed;
		this.dateCreated = dateCreated;
		this.dateSigned = dateSigned;
		this.emailAddress = emailAddress;
		this.fieldId = fieldId;
	}

	public String getTemplateId() {
		return templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getHtmlDocument() {
		return htmlDocument;
	}

	public void setHtmlDocument(String htmlDocument) {
		this.htmlDocument = htmlDocument;
	}

	public String getDataId() {
		return dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	public String getModuleId() {
		return moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getSigned() {
		return signed;
	}

	public void setSigned(Boolean signed) {
		this.signed = signed;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateSigned() {
		return dateSigned;
	}

	public void setDateSigned(Date dateSigned) {
		this.dateSigned = dateSigned;
	}

	public String getEmailAddress() {
		return emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getFieldId() {
		return fieldId;
	}

	public void setFieldId(String fieldId) {
		this.fieldId = fieldId;
	}

}