apiVersion: apps/v1
kind: Deployment
metadata:
  name: escalation
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: escalation
  replicas: 1
  template:
    metadata:
      labels:
        app: escalation
    spec:
      containers:
        - name: escalation
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/escalation:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
