/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubMenuItem } from './subMenuItem';


/**
 * Menu items of menu
 */
export interface MenuItem { 
    /**
     * Route of the menu item
     */
    ROUTE: string;
    /**
     * Order of the menu item
     */
    ORDER: number;
    /**
     * Module of the menu item
     */
    MODULE?: string;
    /**
     * Is menu item a module
     */
    IS_MODULE: boolean;
    /**
     * Path parameter of the menu item
     */
    PATH_PARAMETER?: string;
    /**
     * Icon of the menu item
     */
    ICON?: string;
    /**
     * Is menu item editable
     */
    EDITABLE: boolean;
    /**
     * Name of the menu item
     */
    NAME: string;
    /**
     * Sub menu items of the menu item
     */
    SUB_MENU_ITEMS: Array<SubMenuItem>;
}

