/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sub menu items of the menu item
 */
export interface SubMenuItem { 
    /**
     * Route of the sub menu item
     */
    ROUTE: string;
    /**
     * Order of the sub menu item
     */
    ORDER: number;
    /**
     * Module of the sub menu item
     */
    MODULE?: string;
    /**
     * Is sub item a module
     */
    IS_MODULE: boolean;
    /**
     * Path parameter of the sub menu item
     */
    PATH_PARAMETER?: string;
    /**
     * Icon of the sub menu item
     */
    ICON?: string;
    /**
     * Is menu editable
     */
    EDITABLE: boolean;
    /**
     * Name of the sub menu item
     */
    NAME: string;
}

