/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pageable } from './pageable';
import { Escalation } from './escalation';
import { Sort } from './sort';


export interface PageEscalation { 
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<Escalation>;
    number?: number;
    sort?: Sort;
    first?: boolean;
    numberOfElements?: number;
    pageable?: Pageable;
    last?: boolean;
    empty?: boolean;
}

