apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledgebase
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: knowledgebase
  replicas: 1
  template:
    metadata:
      labels:
        app: knowledgebase
    spec:
      containers:
        - name: knowledgebase
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/knowledgebase:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
