apiVersion: v1
kind: Service
metadata:
  name: knowledgebase-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: knowledgebase
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
