server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/subscribeit/ngdesk
          searchPaths: ngDesk-Config
          #uri: https://github.com/sarat9/config-server-spring-boot
          #searchPaths: config-repo