apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: integration
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
