apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    tier: frontend
    track: pre
spec:
  type: NodePort
  clusterIP: 10.96.27.42
  ports:
  - port: 443
    nodePort: 31308
    targetPort: 443
    name: https
  - port: 80
    nodePort: 32328
    targetPort: 80
    name: http
  - port: 5060
    protocol: TCP
    targetPort: 5060
    name: kam
  - port: 5060
    protocol: UDP
    targetPort: 5060
    name: kam-udp
  selector:
    app: nginx
    tier: frontend
    track: pre
