apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: rest
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
    spec:
      serviceAccount: root-sa
      serviceAccountName: root-sa
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      containers:
        - name: rest
          image: image-registry.openshift-image-registry.svc:5000/NAMESPACE_REPLACE/rest:1
          imagePullPolicy: Always
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          ports:
            - containerPort: 9080
