apiVersion: apps/v1
kind: Deployment
metadata:
  name: module
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: module
  replicas: 1
  template:
    metadata:
      labels:
        app: module
    spec:
      containers:
        - name: module
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/module:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
