apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/auth:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
