apiVersion: v1
kind: Service
metadata:
  name: tesseract-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: tesseract
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
