apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesseract
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: tesseract
  replicas: 1
  template:
    metadata:
      labels:
        app: tesseract
    spec:
      containers:
        - name: tesseract
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/tesseract:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
