apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: data
  replicas: 1
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: data
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/data:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8087