apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidebar
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: sidebar
  replicas: 1
  template:
    metadata:
      labels:
        app: sidebar
    spec:
      containers:
        - name: sidebar
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/sidebar:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
