apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    matchLabels:
      app: report
  replicas: 1
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: gitlab.bluemsp.com:5050/ngdesk/ngdesk/report:latest
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
