package com.ngdesk.notifications.dao;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.Pattern;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Field;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ngdesk.commons.annotations.CustomNotEmpty;
import com.ngdesk.commons.annotations.CustomNotNull;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class Module {

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	@JsonProperty("MODULE_ID")
	private String moduleId;

	@Schema(description = "Name of the module", required = true, example = "books")
	@Field("NAME")
	@JsonProperty("NAME")
	@Pattern(regexp = "^[a-zA-Z0-9_ ]*$", message = "INVALID_MODULE_NAME")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "MODULE_NAME" })
	private String name;

	@JsonProperty("PARENT_MODULE")
	@Field("PARENT_MODULE")
	private String parentModule;

	@Schema(description = "Description of the module", required = false, example = "Module to handle books")
	@CustomNotNull(message = "NOT_NULL", values = { "MODULE_DESCRIPTION" })
	@Field("DESCRIPTION")
	@JsonProperty("DESCRIPTION")
	private String description;

	@Field("SINGULAR_NAME")
	@JsonProperty("SINGULAR_NAME")
	private String singular;

	@Field("PLURAL_NAME")
	@JsonProperty("PLURAL_NAME")
	private String plural;

	@JsonProperty("DATE_CREATED")
	@Field("DATE_CREATED")
	private Date dateCreated;

	@JsonProperty("DATE_UPDATED")
	@Field("DATE_UPDATED")
	private Date dateUpdated;

	@JsonProperty("CREATED_BY")
	@Field("CREATED_BY")
	private String createdBy;

	@JsonProperty("LAST_UPDATED_BY")
	@Field("LAST_UPDATED_BY")
	private String lastUpdatedBy;

	public Module() {
	}

	public Module(String moduleId, String name, String parentModule, String description, String singular, String plural,
			Date dateCreated, Date dateUpdated, String createdBy, String lastUpdatedBy) {
		super();
		this.moduleId = moduleId;
		this.name = name;
		this.parentModule = parentModule;
		this.description = description;
		this.singular = singular;
		this.plural = plural;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getModuleId() {
		return moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getParentModule() {
		return parentModule;
	}

	public void setParentModule(String parentModule) {
		this.parentModule = parentModule;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSingular() {
		return singular;
	}

	public void setSingular(String singular) {
		this.singular = singular;
	}

	public String getPlural() {
		return plural;
	}

	public void setPlural(String plural) {
		this.plural = plural;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}