apiVersion: v1
kind: Service
metadata:
  name: escalation-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: escalation
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
