package com.ngdesk.module.catalogue.dao;

import java.util.Date;
import java.util.List;

import javax.validation.Valid;

import org.springframework.data.annotation.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.ngdesk.commons.annotations.CustomNotEmpty;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class Catalogue {

	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	private String catalogueId;

	@Schema(description = "Name of the Catalogue", required = true, example = "ngDesk customers")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "CATALOGUE_NAME" })
	private String name;

	@Schema(description = "Description of the Catalogue", required = false, example = "Catalogue to handle ngDesk customer requests")
	private String description;

	@Schema(description = "forms", required = true)
	@Valid
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "CATALOGUE_FORMS" })
	private List<CatalogueForm> catalogueForms;

	@Schema(description = "Display Image", required = false)
	private String displayImage;

	private String companyId;

	@Schema(description = "Date Created", required = false, accessMode = AccessMode.READ_ONLY)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	private Date dateCreated;

	@Schema(description = "Date Updated", required = false, accessMode = AccessMode.READ_ONLY)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	private Date dateUpdated;

	@Schema(description = "Last Updated By", required = false, accessMode = AccessMode.READ_ONLY)
	private String lastUpdatedBy;

	@Schema(description = "Created By", required = false, accessMode = AccessMode.READ_ONLY)
	private String createdBy;

	@Schema(description = "visible To", required = false, accessMode = AccessMode.READ_ONLY)
	private List<String> visibleTo;

	public Catalogue() {
	}

	public Catalogue(String catalogueId, String name, String description, @Valid List<CatalogueForm> catalogueForms,
			String displayImage, String companyId, Date dateCreated, Date dateUpdated, String lastUpdatedBy,
			String createdBy, List<String> visibleTo) {
		super();
		this.catalogueId = catalogueId;
		this.name = name;
		this.description = description;
		this.catalogueForms = catalogueForms;
		this.displayImage = displayImage;
		this.companyId = companyId;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
		this.createdBy = createdBy;
		this.visibleTo = visibleTo;
	}

	public String getCatalogueId() {
		return catalogueId;
	}

	public void setCatalogueId(String catalogueId) {
		this.catalogueId = catalogueId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<CatalogueForm> getCatalogueForms() {
		return catalogueForms;
	}

	public void setCatalogueForms(List<CatalogueForm> catalogueForms) {
		this.catalogueForms = catalogueForms;
	}

	public String getDisplayImage() {
		return displayImage;
	}

	public void setDisplayImage(String displayImage) {
		this.displayImage = displayImage;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public List<String> getVisibleTo() {
		return visibleTo;
	}

	public void setVisibleTo(List<String> visibleTo) {
		this.visibleTo = visibleTo;
	}

	

}
