apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: NAMESPACE_REPLACE
spec:
  selector:
    app: workflow
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084

