package com.ngdesk.company.plugin.dao;

import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Field;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ngdesk.commons.annotations.CustomNotEmpty;
import com.ngdesk.commons.annotations.CustomNotNull;

import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema.AccessMode;

public class Plugin {
	
	@Schema(required = false, accessMode = AccessMode.READ_ONLY, description = "Autogenerated Id")
	@Id
	@JsonProperty("PLUGIN_ID")
	private String id;
	
	@Schema(description = "Name of the Plugin", required = true, example = "Chat Plugin")
	@Field("NAME")
	@JsonProperty("NAME")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "PLUGIN_NAME"})
	@CustomNotNull(message = "NOT_NULL", values = { "PLUGIN_NAME"})
	private String name;
	
	@Schema(description = "list of tiers in the Plugin", required = true)
	@Field("TIERS")
	@JsonProperty("TIERS")
	@CustomNotEmpty(message = "DAO_VARIABLE_REQUIRED", values = { "TIERS"})
	@CustomNotNull(message = "NOT_NULL", values = { "TIERS"})
	private List<Tier> tiers;

	public Plugin() {
		super();
	}

	public Plugin(String id, String name, List<Tier> tiers) {
		super();
		this.id = id;
		this.name = name;
		this.tiers = tiers;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Tier> getTiers() {
		return tiers;
	}

	public void setTiers(List<Tier> tiers) {
		this.tiers = tiers;
	}
	
}
